#!/bin/bash

function check() {
    npx -w @poppy-ui/$1 @biomejs/biome $2

    if (( $? != 0 )); then
        echo "Forgot to run $2 on $1 ?"
        exit 1
    fi
}

# Core
check "core" "format"
check "core" "lint"

# Vue
check "vue" "format"
check "vue" "lint"
