name: Archive Download
description: Downloads and decompresses an archive from a previous job
inputs:
  package:
    description: Package name
  node-version:
    description: Node Version
runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.package }}-${{ inputs.node-version }}
        path: ./packages/${{ inputs.package }}/poppy-ui-${{ inputs.package }}-${{ inputs.node-version }}.tgz
