name: Quality
description: Run quality check for specified package
inputs:
  node-version:
    description: The version of node to use.
    type: string
    default: 20.x
    required: false
  upload:
    description: Upload the report
    type: boolean
    default: true
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Package
      run: npm install
      shell: bash

    - name: Format
      run: npx @biomejs/biome format --reporter github
      shell: bash

    - name: Lint
      run: npx @biomejs/biome lint --reporter github
      shell: bash

    - name: Scan
      uses: ajinabraham/njsscan-action@v7
      with:
        args: '. --sarif --output results.sarif || true'

    - name: Upload report
      if: inputs.upload
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
