name: Vue - Audit

on:
  workflow_dispatch:
  push:
    paths:
      - packages/vue/**
      - packages/vue-*/**
  pull_request:
    branches:
      - main
  schedule:
    # Run every Monday-Friday
    # at 6:00 UTC (6:00 am UTC)
    - cron: '00 06 * * 1-5'

# When pushing a new commit we should
# cancel the previous test run to not
# consume more runners than we need to.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Package Dependencies
        run: npx lerna@5 bootstrap --scope @poppy-ui/vue

      - name: Audit
        run: npx audit-ci@latest --config ./audit-ci.json
        working-directory: ./packages/vue