name: Audit

on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - packages/**
  pull_request:
    branches:
      - main
    paths:
      - packages/**
  schedule:
    # Run every Monday-Friday
    # at 6:00 UTC (6:00 am UTC)
    - cron: '00 06 * * 1-5'

# When pushing a new commit we should
# cancel the previous test run to not
# consume more runners than we need to.
concurrency:
  group: ${{ github.ref }}_audit
  cancel-in-progress: true

jobs:
  audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - core
          - react
          - vue
    steps:
      - uses: actions/checkout@v4
      - name: Audit ${{ matrix.package }}
        run: npx -w @poppy-ui/${{ matrix.package }} audit-ci@latest --config ./audit-ci.json
        shell: bash
