name: Build - Core

on:
  push:
    branches:
      - main
    paths:
      - packages/core/**
  pull_request:
    branches:
      - main
    paths:
      - packages/core/**

# When pushing a new commit we should
# cancel the previous test run to not
# consume more runners than we need to.
concurrency:
  group: ${{ github.ref }}_build_core
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.x
          - 22.x
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install -w @poppy-ui/core
        shell: bash

      - name: Build
        run: npm run build -w @poppy-ui/core --if-present
        shell: bash