# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Quality - Vue

on:
  push:
    branches:
      - main
    paths:
      - packages/vue/**
      - packages/vue-*/**
  pull_request:
    branches:
      - main
    paths:
      - packages/vue/**
      - packages/vue-*/**

# When pushing a new commit we should
# cancel the previous test run to not
# consume more runners than we need to.
concurrency:
  group: ${{ github.ref }}_quality_vue
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quality
        uses: ./.github/workflows/actions/quality
        with:
          package: vue

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x
    steps:
      - uses: actions/checkout@v4
      - name: Quality
        uses: ./.github/workflows/actions/test
        with:
          package: vue
          node-version: ${{ matrix.node-version }}
        
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@v3