name: Quality

on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - packages/**
  pull_request:
    branches:
      - main
    paths:
      - packages/**

# When pushing a new commit we should
# cancel the previous test run to not
# consume more runners than we need to.
concurrency:
  group: ${{ github.ref }}_quality
  cancel-in-progress: true

jobs:
  biome:
    name: Format, Lint & Organize Import
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx @biomejs/biome ci --reporter github
        shell: bash

  test-core:
    name: Core
    needs:
      - biome
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.x
          - 22.x
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/test
        with:
          package: core
          node-version: ${{ matrix.node-version }}

  test-react:
    name: React
    needs:
      - biome
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.x
          - 22.x
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare
        run: |
          npm install -w @poppy-ui/core
          npm run build -w @poppy-ui/core
          npm pack -w @poppy-ui/core
          PKG=$(ls poppy-ui-core-*.tgz)
          mv $PKG poppy-ui-core-${{ matrix.node-version }}.tgz
        shell: bash

      - name: Install
        run: |
          npm install ./poppy-ui-core-${{ matrix.node-version }}.tgz -w @poppy-ui/react
          npm install -w @poppy-ui/react
        shell: bash

      - name: Test
        run: npm run test:spec -w @poppy-ui/react --if-present -- --passWithNoTests --coverage
        shell: bash

      - name: Test e2e
        run: npm run test:e2e -w @poppy-ui/react --if-present -- --pass-with-no-tests --reporter github
        shell: bash
      - uses: ./.github/workflows/actions/test
        with:
          package: react
          node-version: ${{ matrix.node-version }}

  test-vue:
    name: Vue
    needs:
      - biome
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.x
          - 22.x
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare
        run: |
          npm install -w @poppy-ui/core
          npm run build -w @poppy-ui/core
          npm pack -w @poppy-ui/core
          PKG=$(ls poppy-ui-core-*.tgz)
          mv $PKG poppy-ui-core-${{ matrix.node-version }}.tgz
          npm pack -w @poppy-ui/docs
          PKG=$(ls poppy-ui-docs-*.tgz)
          mv $PKG poppy-ui-docs-${{ matrix.node-version }}.tgz
        shell: bash

      - name: Install
        run: |
          npm install ./poppy-ui-core-${{ matrix.node-version }}.tgz -w @poppy-ui/vue
          npm install -D ./poppy-ui-docs-${{ matrix.node-version }}.tgz -w @poppy-ui/vue
          npm install -w @poppy-ui/vue
        shell: bash

      - name: Test
        run: npm run test:spec -w @poppy-ui/vue --if-present -- --passWithNoTests --coverage
        shell: bash

      - name: Test e2e
        run: npm run test:e2e -w @poppy-ui/vue --if-present -- --pass-with-no-tests --reporter github
        shell: bash
      - uses: ./.github/workflows/actions/test
        with:
          package: vue
          node-version: ${{ matrix.node-version }}
