# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Quality
 
on:
  push:
    branches:
      - main
    paths:
      - packages/**
  pull_request:
    branches:
      - main
    paths:
      - packages/**

# When pushing a new commit we should
# cancel the previous test run to not
# consume more runners than we need to.
concurrency:
  group: ${{ github.ref }}_quality
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quality
        uses: ./.github/workflows/actions/quality

  test:
    needs: quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - core
          - vue
        node-version:
          - 18.x
          - 20.x
          - 22.x
    steps:
      - uses: actions/checkout@v4
      - name: Test ${{ matrix.package }} on ${{ matrix.node-version }}
        uses: ./.github/workflows/actions/test
        with:
          package: ${{ matrix.package }}
          node-version: ${{ matrix.node-version }}

  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@v3