name: Audit
description: Audit provided package
inputs:
  package:
    description: Audited package
    type: string
    required: true
  node-version:
    description: Node version
    type: string
    required: false
    default: 20.x

runs:
  using: composite
  steps:
    - run: npx -w @poppy-ui/${{ inputs.package }} audit-ci@latest --config ./audit-ci.json
      shell: bash
